services:
  - type: web
    name: android-cloud
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: WEB_VNC
        value: "true"
    ports:
      - 6080
      
